name: Packer build pipeline
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bash ${GITHUB_WORKSPACE}/install_packer.sh
      - run: cd ${GITHUB_WORKSPACE}/wsl && packer build Ubuntu-2404.pkr.hcl