name: Build and Release WSL Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  

jobs:
  build-packer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Packer
        uses: hashicorp/setup-packer@v3
        with:
          packer_version: latest

      - name: Initialize Packer
        run: packer init wsl/Wsl-tpl-builder.pkr.hcl

      - name: Validate Packer template
        run: packer validate wsl/Wsl-tpl-builder.pkr.hcl

      - name: Build Packer image
        run: packer build -force wsl/Wsl-tpl-builder.pkr.hcl

      - name: Rename artifact
        run: |
          mkdir artifacts
          gzip output/DevOps-ubuntu.tar output/DevOps-ubuntu.tar.gz
          cp output/DevOps-ubuntu.tar.gz artifacts/DevOps-ubuntu.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wsl-template
          path: artifacts/

  release:
    needs: build-packer
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: wsl-template

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
